-- Veroro 분석 엔진 DB 적재 (Stage 3)
-- 성분 사전/규칙을 코드에서 DB로 분리: analysis_rules 신규 + allergens/ingredient_synonyms 시드
-- 멱등(idempotent)하게 작성됨. 운영 적용 전 검토용.

BEGIN;

-- ───────────────────────────────────────────────
-- 1. analysis_rules 테이블 (규칙 엔진의 선언적 규칙 저장소)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.analysis_rules (
  id               text PRIMARY KEY,
  target           text NOT NULL,
  species          text,
  condition        jsonb NOT NULL DEFAULT '{}'::jsonb,
  severity         text NOT NULL,
  score_delta      integer NOT NULL DEFAULT 0,
  title            text NOT NULL,
  message_template text NOT NULL,
  evidence_level   text NOT NULL,
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.analysis_rules ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='analysis_rules' AND policyname='analysis_rules_read') THEN
    CREATE POLICY analysis_rules_read ON public.analysis_rules FOR SELECT USING (true);
  END IF;
END $$;

-- ───────────────────────────────────────────────
-- 2. allergens 시드
-- ───────────────────────────────────────────────
INSERT INTO public.allergens (code, display_name_ko)
SELECT v.code, v.name FROM (VALUES
  ('beef', '소고기'),
  ('chicken', '닭'),
  ('corn', '옥수수'),
  ('duck', '오리'),
  ('egg', '계란'),
  ('fish', '생선'),
  ('gluten', '글루텐'),
  ('grain', '곡물'),
  ('lamb', '양고기'),
  ('legume', '두류'),
  ('pork', '돼지고기'),
  ('poultry', '가금류'),
  ('soy', '대두'),
  ('turkey', '칠면조'),
  ('wheat', '밀')
) AS v(code, name)
WHERE NOT EXISTS (SELECT 1 FROM public.allergens a WHERE a.code = v.code);

-- ───────────────────────────────────────────────
-- 3. analysis_rules 시드 (코드 rules.ts와 동기화)
-- ───────────────────────────────────────────────
INSERT INTO public.analysis_rules (id,target,species,condition,severity,score_delta,title,message_template,evidence_level) VALUES
  ('DOG_XYLITOL_DANGER','ingredient','dog','{"hasIngredient":"자일리톨"}'::jsonb,'danger',-100,'개에게 위험한 감미료','자일리톨은 개에게 매우 위험할 수 있어요. 섭취 가능성이 있다면 급여하지 않는 것이 안전합니다.','veterinary'),
  ('DOG_GRAPE_RAISIN_DANGER','ingredient','dog','{"hasAnyIngredient":["포도","건포도"]}'::jsonb,'danger',-100,'개에게 위험할 수 있는 과일 성분','포도·건포도는 일부 개에서 신장 손상 위험이 보고되어 있어요.','veterinary'),
  ('ALLIUM_DANGER','ingredient','both','{"hasAnyIngredient":["양파","마늘","파","부추"]}'::jsonb,'danger',-90,'반려동물에게 피해야 할 파속 식물','양파·마늘류는 반려동물에게 위험할 수 있어요. 원료에 포함되어 있다면 급여 전 수의사 상담이 필요합니다.','veterinary'),
  ('CHOCOLATE_CAFFEINE_DANGER','ingredient','both','{"hasAnyIngredient":["초콜릿","코코아","카페인","커피"]}'::jsonb,'danger',-100,'카페인·초콜릿 계열 주의','초콜릿·카페인 계열 성분은 반려동물에게 위험할 수 있어요.','veterinary'),
  ('MACADAMIA_DANGER','ingredient','dog','{"hasIngredient":"마카다미아"}'::jsonb,'danger',-100,'개에게 위험한 견과류','마카다미아는 개에게 위험할 수 있어요.','veterinary'),
  ('CAT_PROPYLENE_GLYCOL','ingredient','cat','{"hasIngredient":"프로필렌글리콜"}'::jsonb,'caution',-25,'고양이에게 권장되지 않는 습윤제','프로필렌 글리콜은 특히 고양이에게는 권장되지 않는 성분이에요.','veterinary'),
  ('SYNTHETIC_PRESERVATIVE','ingredient','both','{"hasAnyIngredient":["BHA","BHT","에톡시퀸"]}'::jsonb,'caution',-10,'합성 산화방지제','합성 산화방지제(BHA·BHT·에톡시퀸)가 사용됐어요. 천연 보존제(혼합 토코페롤·로즈마리 추출물 등)에 비해 논란이 있는 성분이에요.','internal_policy'),
  ('VAGUE_ANIMAL_SOURCE','ingredient','both','{"hasRiskTag":"controversial","hasCategory":"processed_protein"}'::jsonb,'watch',-8,'출처가 불명확한 동물성 원료','동물 기원이 구체적으로 표시되지 않은 원료가 있어요. 출처가 명확한 표기(예: 닭고기분)가 더 좋아요.','internal_policy'),
  ('FIRST_INGREDIENT_ANIMAL_PROTEIN','product','both','{"firstIngredientCategory":"animal_protein"}'::jsonb,'good',10,'명확한 동물성 단백질','첫 번째 원료가 명확한 동물성 단백질이라 주요 단백질원이 비교적 분명해요.','nutrition_guideline'),
  ('OMEGA3_PRESENT','ingredient','both','{"hasAnyIngredient":["연어오일","어유"]}'::jsonb,'good',3,'오메가-3 공급원','오메가-3(연어 오일·어유)가 포함돼 피부·관절 건강에 도움이 될 수 있어요.','nutrition_guideline'),
  ('JOINT_SUPPORT','ingredient','both','{"hasAnyIngredient":["글루코사민","콘드로이친"]}'::jsonb,'good',3,'관절 보조 성분','글루코사민·콘드로이친 등 관절 보조 성분이 포함돼 있어요.','nutrition_guideline'),
  ('NATURAL_PRESERVATIVE','ingredient','both','{"hasAnyIngredient":["혼합토코페롤","로즈마리추출물"]}'::jsonb,'good',2,'천연 산화방지제','혼합 토코페롤·로즈마리 추출물 등 천연 보존제를 사용했어요.','internal_policy')
ON CONFLICT (id) DO UPDATE SET
  target=EXCLUDED.target, species=EXCLUDED.species, condition=EXCLUDED.condition,
  severity=EXCLUDED.severity, score_delta=EXCLUDED.score_delta, title=EXCLUDED.title,
  message_template=EXCLUDED.message_template, evidence_level=EXCLUDED.evidence_level, updated_at=now();

-- ───────────────────────────────────────────────
-- 4. ingredient_synonyms 시드
--    사전의 alias/영문명을 기존 ingredients(name_ko 일치)에 연결.
--    일치하는 ingredient가 없으면 조용히 건너뜀.
-- ───────────────────────────────────────────────
INSERT INTO public.ingredient_synonyms (ingredient_id, synonym_name, language)
SELECT i.id, v.syn, v.lang
FROM (VALUES
  ('닭고기','chicken','en'),
  ('닭고기','닭','ko'),
  ('닭고기','계육','ko'),
  ('닭고기','치킨','ko'),
  ('닭고기','chicken','en'),
  ('닭고기','닭가슴살','ko'),
  ('닭고기','생닭고기','ko'),
  ('닭고기','닭 신선육','ko'),
  ('닭고기','닭신선육','ko'),
  ('소고기','beef','en'),
  ('소고기','소','ko'),
  ('소고기','우육','ko'),
  ('소고기','비프','ko'),
  ('소고기','beef','en'),
  ('소고기','쇠고기','ko'),
  ('소고기','생소고기','ko'),
  ('돼지고기','pork','en'),
  ('돼지고기','돼지','ko'),
  ('돼지고기','돈육','ko'),
  ('돼지고기','포크','ko'),
  ('돼지고기','pork','en'),
  ('오리고기','duck','en'),
  ('오리고기','오리','ko'),
  ('오리고기','생오리','ko'),
  ('오리고기','오리 신선육','ko'),
  ('오리고기','duck','en'),
  ('양고기','lamb','en'),
  ('양고기','양','ko'),
  ('양고기','램','ko'),
  ('양고기','lamb','en'),
  ('양고기','램미트','ko'),
  ('칠면조','turkey','en'),
  ('칠면조','칠면조고기','ko'),
  ('칠면조','터키','ko'),
  ('칠면조','turkey','en'),
  ('칠면조','칠면조 신선육','ko'),
  ('연어','salmon','en'),
  ('연어','생연어','ko'),
  ('연어','salmon','en'),
  ('연어','연어살','ko'),
  ('참치','tuna','en'),
  ('참치','가다랑어','ko'),
  ('참치','다랑어','ko'),
  ('참치','tuna','en'),
  ('참치','bonito','en'),
  ('흰살생선','whitefish','en'),
  ('흰살생선','대구','ko'),
  ('흰살생선','명태','ko'),
  ('흰살생선','황태','ko'),
  ('흰살생선','월아이','ko'),
  ('흰살생선','whitefish','en'),
  ('흰살생선','cod','en'),
  ('계란','egg','en'),
  ('계란','달걀','ko'),
  ('계란','통달걀','ko'),
  ('계란','전란','ko'),
  ('계란','egg','en'),
  ('계란','건조란','ko'),
  ('계육분','chicken meal','en'),
  ('계육분','닭고기분','ko'),
  ('계육분','치킨밀','ko'),
  ('계육분','chicken meal','en'),
  ('계육분','닭고기분말','ko'),
  ('계육분','계육 분말','ko'),
  ('어분','fish meal','en'),
  ('어분','생선분','ko'),
  ('어분','fish meal','en'),
  ('어분','어류분말','ko'),
  ('가수분해 동물 단백질','hydrolyzed animal protein','en'),
  ('가수분해 동물 단백질','가수분해단백','ko'),
  ('가수분해 동물 단백질','가수분해 단백질','ko'),
  ('가수분해 동물 단백질','hydrolyzed protein','en'),
  ('부산물','by-product','en'),
  ('부산물','육분','ko'),
  ('부산물','동물성단백질','ko'),
  ('부산물','가금류부산물','ko'),
  ('부산물','가금육분','ko'),
  ('부산물','meal','en'),
  ('부산물','by-product','en'),
  ('부산물','동물성 단백질','ko'),
  ('쌀','rice','en'),
  ('쌀','백미','ko'),
  ('쌀','싸라기','ko'),
  ('쌀','미강','ko'),
  ('쌀','rice','en'),
  ('현미','brown rice','en'),
  ('현미','brown rice','en'),
  ('현미','현미분','ko'),
  ('귀리','oat','en'),
  ('귀리','오트','ko'),
  ('귀리','oat','en'),
  ('귀리','oatmeal','en'),
  ('귀리','압착귀리','ko'),
  ('보리','barley','en'),
  ('보리','barley','en'),
  ('보리','보리쌀','ko'),
  ('밀','wheat','en'),
  ('밀','밀가루','ko'),
  ('밀','소맥분','ko'),
  ('밀','밀 글루텐','ko'),
  ('밀','밀글루텐','ko'),
  ('밀','wheat','en'),
  ('밀','wheat gluten','en'),
  ('옥수수','corn','en'),
  ('옥수수','옥수수가루','ko'),
  ('옥수수','옥수수글루텐','ko'),
  ('옥수수','옥수수 글루텐','ko'),
  ('옥수수','콘글루텐','ko'),
  ('옥수수','corn','en'),
  ('옥수수','corn gluten','en'),
  ('감자','potato','en'),
  ('감자','건조감자','ko'),
  ('감자','건조 감자','ko'),
  ('감자','potato','en'),
  ('감자','감자전분','ko'),
  ('고구마','sweet potato','en'),
  ('고구마','sweet potato','en'),
  ('고구마','고구마분','ko'),
  ('타피오카','tapioca','en'),
  ('타피오카','tapioca','en'),
  ('타피오카','타피오카전분','ko'),
  ('완두','pea','en'),
  ('완두','완두콩','ko'),
  ('완두','완두단백','ko'),
  ('완두','완두 섬유','ko'),
  ('완두','완두섬유','ko'),
  ('완두','pea','en'),
  ('완두','pea protein','en'),
  ('완두','pea fiber','en'),
  ('렌틸콩','lentil','en'),
  ('렌틸콩','렌틸','ko'),
  ('렌틸콩','lentil','en'),
  ('병아리콩','chickpea','en'),
  ('병아리콩','병아리 콩','ko'),
  ('병아리콩','chickpea','en'),
  ('병아리콩','garbanzo','en'),
  ('대두','soybean','en'),
  ('대두','콩','ko'),
  ('대두','소이빈','ko'),
  ('대두','대두박','ko'),
  ('대두','soybean','en'),
  ('대두','soy','en'),
  ('닭지방','chicken fat','en'),
  ('닭지방','닭 지방','ko'),
  ('닭지방','chicken fat','en'),
  ('연어오일','salmon oil','en'),
  ('연어오일','연어유','ko'),
  ('연어오일','연어 오일','ko'),
  ('연어오일','salmon oil','en'),
  ('연어오일','fish oil','en'),
  ('연어오일','어유','ko'),
  ('해바라기유','sunflower oil','en'),
  ('해바라기유','해바라기씨유','ko'),
  ('해바라기유','sunflower oil','en'),
  ('카놀라유','canola oil','en'),
  ('카놀라유','유채유','ko'),
  ('카놀라유','canola oil','en'),
  ('카놀라유','rapeseed oil','en'),
  ('코코넛오일','coconut oil','en'),
  ('코코넛오일','코코넛 오일','ko'),
  ('코코넛오일','coconut oil','en'),
  ('코코넛오일','mct','en'),
  ('혼합토코페롤','mixed tocopherols','en'),
  ('혼합토코페롤','혼합 토코페롤','ko'),
  ('혼합토코페롤','토코페롤','ko'),
  ('혼합토코페롤','비타민e','en'),
  ('혼합토코페롤','mixed tocopherols','en'),
  ('혼합토코페롤','vitamin e','en'),
  ('로즈마리추출물','rosemary extract','en'),
  ('로즈마리추출물','로즈마리 추출물','ko'),
  ('로즈마리추출물','rosemary extract','en'),
  ('글리세린','glycerin','en'),
  ('글리세린','식물성글리세린','ko'),
  ('글리세린','글리세롤','ko'),
  ('글리세린','glycerin','en'),
  ('글리세린','glycerine','en'),
  ('글리세린','vegetable glycerin','en'),
  ('BHA','BHA','en'),
  ('BHA','부틸하이드록시아니솔','ko'),
  ('BHA','bha','en'),
  ('BHA','butylated hydroxyanisole','en'),
  ('BHT','BHT','en'),
  ('BHT','부틸하이드록시톨루엔','ko'),
  ('BHT','bht','en'),
  ('BHT','butylated hydroxytoluene','en'),
  ('에톡시퀸','ethoxyquin','en'),
  ('에톡시퀸','ethoxyquin','en'),
  ('프로필렌글리콜','propylene glycol','en'),
  ('프로필렌글리콜','프로필렌 글리콜','ko'),
  ('프로필렌글리콜','propylene glycol','en'),
  ('타우린','taurine','en'),
  ('타우린','taurine','en'),
  ('L-카르니틴','L-carnitine','en'),
  ('L-카르니틴','카르니틴','ko'),
  ('L-카르니틴','l-carnitine','en'),
  ('L-카르니틴','carnitine','en'),
  ('글루코사민','glucosamine','en'),
  ('글루코사민','glucosamine','en'),
  ('콘드로이친','chondroitin','en'),
  ('콘드로이친','chondroitin','en'),
  ('칼슘','calcium','en'),
  ('칼슘','탄산칼슘','ko'),
  ('칼슘','calcium','en'),
  ('칼슘','calcium carbonate','en'),
  ('유산균','probiotics','en'),
  ('유산균','프로바이오틱스','ko'),
  ('유산균','락토바실러스','ko'),
  ('유산균','probiotics','en'),
  ('유산균','lactobacillus','en'),
  ('유산균','프락토올리고당','ko'),
  ('유산균','fos','en'),
  ('자일리톨','xylitol','en'),
  ('자일리톨','자이리톨','ko'),
  ('자일리톨','xylitol','en'),
  ('자일리톨','자일리톨감미료','ko'),
  ('양파','onion','en'),
  ('양파','양파분말','ko'),
  ('양파','onion','en'),
  ('양파','onion powder','en'),
  ('마늘','garlic','en'),
  ('마늘','마늘분말','ko'),
  ('마늘','garlic','en'),
  ('마늘','garlic powder','en'),
  ('파','green onion','en'),
  ('파','대파','ko'),
  ('파','쪽파','ko'),
  ('파','부추','ko'),
  ('파','chive','en'),
  ('파','leek','en'),
  ('파','scallion','en'),
  ('포도','grape','en'),
  ('포도','건포도','ko'),
  ('포도','grape','en'),
  ('포도','raisin','en'),
  ('초콜릿','chocolate','en'),
  ('초콜릿','코코아','ko'),
  ('초콜릿','chocolate','en'),
  ('초콜릿','cocoa','en'),
  ('초콜릿','cacao','en'),
  ('카페인','caffeine','en'),
  ('카페인','커피','ko'),
  ('카페인','caffeine','en'),
  ('카페인','coffee','en'),
  ('마카다미아','macadamia','en'),
  ('마카다미아','마카다미아너트','ko'),
  ('마카다미아','macadamia','en')
) AS v(canonical_ko, syn, lang)
JOIN public.ingredients i ON i.name_ko = v.canonical_ko
WHERE NOT EXISTS (
  SELECT 1 FROM public.ingredient_synonyms s
  WHERE s.ingredient_id = i.id AND s.synonym_name = v.syn
);

COMMIT;
